netlify/renovate-config

go/default.json
This way other repos can reference this config (and we can grow it). They should be able to use the `extends["github>netlify/renovate-config//go/default"]`
=> make a go/default.json

default.json
Please note that renovate applies all matching rules (doesn't stop at the first matching one)
=> chore: group only Netlify Build packages

rust-default.json
stolen with no changes from here: https://github.com/netlify/renovate-rust-preset/blob/main/renovate.json
If this gets merged, I think it could be worth archiving the other repo and we can migrate any rust services as we run into them (no rush)
=> add rust defaults

rust-default.json
'chore' commits don't count as 'user-facing' for release-please, which
means we have to push dummy commits just to poke release-please after we
update dependencies.
Using `fix(deps)`, we 1) still see it's for deps, 2) poke release-please
as soon as we merge renovate PRs.
Discussed with @mraerino ahead of time.
=> feat: Set semanticCommitType to fix

default.json
Background in https://github.com/netlify/netlify-headers-parser/pull/34
`escape-string-regexp@v5` requires Node 12 and ES modules.
=> fix: add `escape-string-regexp`

default.json
`filter-obj@3` requires ES modules and Node 12.
=> fix: add `filter-obj`

default.json
Related to https://github.com/netlify/team-dev/issues/30
Last round of packages updates from the CLI repo
=> chore: ignore packages versions that require Node.js >= 12

default.json
`node-fetch@3` requires ES modules + Node 12.20.0
=> fix: add `node-fetch` exception

default.json
`p-locate@v6` requires Node 12 and ES modules.
=> chore: add `p-locate@v6` exception

default.json
`get-port@v6` requires ES modules and Node 12.
=> fix: add `get-port` exception

default.json
`boxen@v6` requires ES modules and Node 12.
=> fix: add exception for `boxen`

default.json
When a repo requires a branch to be up to date before merging, renovate rebases PRs on each change to the default branch.
Since we already use Kodiak to keep branches up to date, and it does it more efficiently (just before merging the PR, and not on each change to the default branch), this PR configures renovate to only rebase when a PR is conflicted.
See https://docs.renovatebot.com/configuration-options/#rebasewhen
=> chore: change renovate to rebase only on conflicts

default.json
Since `zip-it-and-ship-it` is a dependency of `netlify/build` it makes sense to group those to avoid different versions of `zip-it-and-ship-it` being used in Netlify CLI
=> chore: group zisi with build dependencies

default.json
`pino@7` does not support Node 10.
=> chore: add exception for `pino`

default.json
`p-event@v5` does not support Node 10 and requires native ES modules, so we cannot upgrade yet.
=> chore: add rule for `p-event@5`

default.json
This adds a rule for `process-exists@5` because it drops support for Node 10 and requires native ES modules.
=> chore: add rule for `process-exists`

default.json
This adds a rule for `ps-list@8` since that version drops support for Node 10 and requires native ES modules.
=> chore: add rule for `ps-list@8`

default.json
We should make the JS spceific package rules specific to the `npm` manager. This will make it easier for projects like `buildbot` to use these rules together with other package manager rules - https://github.com/netlify/buildbot/issues/1842
=> chore(node): make our packageRules more specific

default.json
Reverts netlify/renovate-config#56 - we're seeing a lot of `lockfileMaintenance` PRs across our repos and we can't really pinpoint what's behind it, with this change being the only thing that took place over the last couple of days.
=> Revert "chore(node): make our packageRules more specific"

default.json
Execa v6 requires native ES modules, so we cannot yet upgrade to it.
=> fix: add `execa@v6`

default.json
`sort-on@v5` requires pure ES modules so we cannot use it yet.
=> fix: add `sort-on@v5`

default.json
Most repositories use `renovate-config` as their source of truth. However, `netlify/build` still defines multiple rules [in its own file](https://github.com/netlify/build/blob/main/renovate.json5). Most of those are related to dependencies which cannot be upgraded due to the currently supported Node.js version.
This PR merges all those rules to our shared configuration, so that `renovate.json5` in `netlify/build` can just use the shared list.
This PR also fixes the alphabetical order of the list.
=> chore: merge all rules from `netlify/build`

default.json
This fixes a syntax error in `default.json`.
=> fix: dangling comma in JSON

default.json
This adds an exception for `test-each@v3` since it requires pure ES modules.
=> fix: add `test-each` exception

default.json
`read-pkg@v6` cannot be upgraded because it requires pure ES modules.
=> chore: add `read-pkg` exception

default.json
This adds [the rules from the `js-client`](https://github.com/netlify/js-client/blob/main/renovate.json5) so we can simplify the `renovate.json5` in that repository.
=> chore: add rules from `js-client`

default.json
`chalk@v5` requires pure ES modules, so we cannot use it yet.
=> fix: add `chalk@v5` exception

default.json
Now that we've dropped Node 10 support, some dependencies can be upgraded.
Most of the dependencies still require pure ES modules support unfortunately (see https://github.com/netlify/pod-workflow/issues/321).
=> fix: re-enable some dependencies related to Node 10 support

default.json
Yet another attempt at https://github.com/netlify/renovate-config/pull/56 once we realised https://github.com/netlify/renovate-config/pull/57 didn't actually do anything - https://netlify.slack.com/archives/CN8S7NB29/p1636744799215700?thread_ts=1636647481.193300&cid=CN8S7NB29
=> chore: make npm rules specific to npm

default.json
We added this constraint to force an old version of `npm` to keep old version of lock files (see https://github.com/netlify/renovate-config/pull/4)
I think we can remove it now
=> fix(node): remove Node.js constraint

default.json
Going to disable this until https://github.com/renovatebot/renovate/issues/13014 is resolved, as it creates too much noise (a PR almost every 1-2 hours for every Node.js/JS repo).
=> chore: disable lock file management

default.json
This adds more exceptions for packages which require pure ES modules, since we have not completed migration yet.
=> chore: add exceptions for pure ESM dependencies

default.json
This adds an exception for `dot-prop@v7` since this version requires pure ES modules.
=> chore: add exception for `dot-prop`

default.json, shared.json
Part of https://github.com/netlify/team-dev/issues/36
This allows `is-plain-obj` to be upgraded for ESM-migrated repositories.
This is mostly meant to try out the new configuration.
=> chore: upgrade `is-plain-obj` for ESM migrated repositories

rust-default.json
=> chore: Group webpki-* packages under rustls

shared.json
`pretty-bytes@v6` requires Node 14. This PR adds a rule to not upgrade it while we still support Node 12.
=> chore: add exception for `pretty-bytes`

go-default.json
This will also pick up when the current version is set as `v2` or `v2.11`
=> Support different semver variations for KSG

go-default.json
This is kinda getting out of hand 😅 
Regex101 to understand & verify the regex: https://regex101.com/r/HWWplq/1
This adds two things:
- Detect values that are quoted (yes, technically invalid yaml would be detected, but that should be irrelevant here)
- Allow suffixes after the version
Would i rather just use a yaml parser? Yes!
Do i have the time to teach that to renovate? No.
=> Expand ksg version matching

shared.json
This was [done](https://github.com/netlify/cli/pull/5157) in the CLI already to test this out and it [instantly started working](https://github.com/netlify/cli/pull/5158).
`matchers` in packageRules are combined with AND which makes the netlify grouping not match anything.
=> fix: fix config to correctly group netlify packages

go-default.json
We sometimes use Go modules pinned to a specific commit instead of a tag.
Renovate by default then produces an update for every new commit to that repo.
Instead, we'll likely only want to update the dependency manually or when there is a newer tag available.
This change makes it so that these `digest` type updates are only put into an issue and not created as a PR.
My understanding is that we'll still get a PR for when there was a new tag on the dependency.
=> Avoid creating PRs for digest updates

shared.json
These packages were locked because of Node.js 14, so it is finally time to allow updates for them.
=> chore: remove locked packages

go-default.json
These can be used to updated versions in places where renovate is not able to detect a dependency. See https://docs.renovatebot.com/presets-regexManagers/
=> Include some useful regex manager presets

go-default.json
- Re-enable the Docker manager: We sometimes build Go binaries inside of docker and should keep the Go version up to date. Example: https://github.com/netlify/socketeer/blob/0cff37add5cb85ae365b7875a88ed39ebd1a571c/Dockerfile#L5
- Group Go updates: Opens only a single PR for updating the Go version in multiple places
=> Improve Go rules

go-default.json
This will help with notification overload from renovate after every merge.
Since we're mostly using merge queues, we don't care that a PR is up-to-date before we add it to the queue.
=> Reduce noise from rebases in Go preset
